config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :test_models

  get 'test/index'

  get 'test/restful'

  get 'test/rss'

  get 'test/get_dk2_game_image'

  get 'test/geo_map'

  devise_for :users, controllers: {sessions: "users/sessions"}

  mount KomachiHeartbeat::Engine => "/ops"

  root 'test#index'

  mount Sidekiq::Web => '/sidekiq'

end

app/models/test_model.rb
class TestModel < ActiveRecord::Base
  turntable :user_cluster, :id
  
  sequencer :user_seq_1
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #turntable :user_cluster, :id
  
  #sequencer :user_seq_1

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
    if request.xhr?
      #render body: "{\"a\": \"b\"}"
      render json: {a: "b"}
    end

    #HardWorker.perform_async('bob', 5)
  end

  def rss
    @dk2_game_entries = Dk2RssEntry.newest_entries
  end

  def get_dk2_game_image
    image = Dk2RssEntry.get_image_file_cached(params[:url])
    type = MIME::Types.type_for(params[:url])[0].to_s
    send_data(image, :disposition => "inline", :type => type)
  end

  def geo_map
    
  end

end

app/controllers/test_models_controller.rb
class TestModelsController < ApplicationController
  before_action :set_test_model, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @test_models = TestModel.all
    respond_with(@test_models)
  end

  def show
    respond_with(@test_model)
  end

  def new
    @test_model = TestModel.new
    respond_with(@test_model)
  end

  def edit
  end

  def create
    @test_model = TestModel.new(test_model_params)
    @test_model.save
    respond_with(@test_model)
  end

  def update
    @test_model.update(test_model_params)
    respond_with(@test_model)
  end

  def destroy
    @test_model.destroy
    respond_with(@test_model)
  end

  private
    def set_test_model
      @test_model = TestModel.find(params[:id])
    end

    def test_model_params
      params.require(:test_model).permit(:task)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    #binding.pry
    self.resource = warden.authenticate!(auth_options)
    #self.resource = User.find(2);
    set_flash_message(:notice, :signed_in) if is_flashing_format?
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/test_models_helper.rb
module TestModelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ori</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <!--<script type="text/javascript" src="js/jquery.ajax-cross-origin.min.js"></script>-->
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display http://getbootstrap.com/components/ -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Ori</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Ideas</a></li>
          <li><%= link_to 'Monitoring', sidekiq_web_path %></li>
        </ul>
          <p class="navbar-text pull-right">
            <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong>.
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
            <% end %>
          </p>
      </div>
    </div>
  </nav>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>

  <footer>
    <div class="container">
      Rails 2015
    </div>
  </footer>
</body>

<%= javascript_tag do %>

/*
  $( "form" ).addClass( "form-horizontal" );
  $( "form div" ).addClass( "form-group" );
  $( "form label" ).addClass( "col-sm-3 control-label" );
  $( "form input:visible" ).not( "input[name='commit']" ).addClass( "form-control" );
  $( "form input:visible" ).not( "input[name='commit']" ).wrap( "<div class='col-sm-4'></div>" );
  $( "br" ).remove();

  $( "input[name='commit']" ).addClass( "btn btn-primary" ); 
  $( "input[name='commit']" ).wrap( "<div class='col-sm-offset-3 col-sm-4'></div>" );
*/

<% end %>

</html>

app/views/test_models/_form.html.erb
<%= form_for(@test_model) do |f| %>
  <% if @test_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_model.errors.count, "error") %> prohibited this test_model from being saved:</h2>

      <ul>
      <% @test_model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task %><br>
    <%= f.text_field :task %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_models/edit.html.erb
<h1>Editing test_model</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_model %> |
<%= link_to 'Back', test_models_path %>

app/views/test_models/index.html.erb
<h1>Listing test_models</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @test_models.each do |test_model| %>
      <tr>
        <td><%= test_model.task %></td>
        <td><%= link_to 'Show', test_model %></td>
        <td><%= link_to 'Edit', edit_test_model_path(test_model) %></td>
        <td><%= link_to 'Destroy', test_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test model', new_test_model_path %>

app/views/test_models/new.html.erb
<h1>New test_model</h1>

<%= render 'form' %>

<%= link_to 'Back', test_models_path %>

app/views/test_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @test_model.task %>
</p>

<%= link_to 'Edit', edit_test_model_path(@test_model) %> |
<%= link_to 'Back', test_models_path %>